apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config
  namespace: homework
data:
  file: |
    server {
        listen 80;
        server_name homework.otus;
        location / {
            proxy_pass http://localhost:8000;
        }
    }