apiVersion: v1
kind: Pod
metadata:
  name: first-app
  namespace: homework
spec:
  volumes:
    - name: app-volume
      emptyDir: { }
    - name: config-volume
      configMap:
        name: nginx-config
  initContainers:
    - name: init
      image: alpine/git
      command:
        ["git", "clone", "https://github.com/thrashches/design_studio.git", "/init"]
      volumeMounts:
        - mountPath: /init
          name: app-volume
  containers:
    - name: nginx-app
      image: nginx:latest
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /homework
          name: app-volume
        - mountPath: /etc/nginx/conf.d
          name: config-volume
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-rf", "/homework/*"]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    server {
      listen 8000;
      location / {
        try_files $uri $uri/ /index.html;
        root /homework;
        index  index.html index.htm;
      }
    }

